# VacationPy
----
#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import gmaps.datasets

# Import API key
from api_keys import g_key

In [2]:
# Configure gmaps
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
#load the csv
cities = "city_data.csv"
cities_df = pd.read_csv(cities)
cities_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Saskylakh,71.9167,114.0833,-22.99,83,0,7.78,RU,1613000207
1,Saint-Pierre,-21.3393,55.4781,78.80,69,0,6.91,RE,1613000207
2,Batagay-Alyta,67.8006,130.4114,-7.87,88,9,1.12,RU,1613000207
3,Luebo,-5.3500,21.4167,71.06,94,100,1.39,CD,1613000207
4,Hong Kong,22.2855,114.1577,62.01,84,54,7.67,HK,1613000208

In [4]:
#store latitude and longitude in cities_locations
cities_location = cities_df[["Lat", "Lng"]].astype(float) 
humidity = cities_df["Humidity"].astype(float)

In [6]:
#ploting the humidity heatmap

fig = gmaps.figure()
max_intensity = np.max(humidity)

heat_layer = gmaps.heatmap_layer(cities_location, weights=humidity, max_intensity = 100, dissipating=False, point_radius = 2)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [7]:
#narrow with conditions Max Temp > 70 AND <80, Wind Speed <=10 and Cloudiness < 15.

narrow_cities_df = cities_df.loc[(cities_df["Max Temp"] > 70) & 
                                 (cities_df["Max Temp"] < 80) & 
                                 (cities_df["Wind Speed"] <= 10) &
                                 (cities_df["Cloudiness"] < 15)].dropna() 

narrow_cities_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
1,Saint-Pierre,-21.3393,55.4781,78.80,69,0,6.91,RE,1613000207
28,Saint-Philippe,-21.3585,55.7679,78.80,69,0,6.91,RE,1613000214
93,Belmonte,-15.8631,-38.8828,77.00,78,0,8.05,BR,1613000231
127,Cabo San Lucas,22.8909,-109.9124,75.99,47,0,1.99,MX,1613000239
138,Niamey,13.5137,2.1098,78.80,15,0,3.44,NE,1613000242
169,Arteaga,18.4667,-102.4167,70.20,64,0,6.51,MX,1613000251
196,Lakes Entrance,-37.8811,147.9810,79.00,60,0,8.01,AU,1613000258
208,Sinaloa,25.0000,-107.5000,77.00,52,0,3.00,MX,1613000261
256,Harper,4.3750,-7.7169,78.96,87,13,7.76,LR,1613000287
309,Batemans Bay,-35.7167,150.1833,71.01,76,4,10.00,AU,1613000302
321,Ancud,-41.8697,-73.8203,75.20,53,0,5.75,CL,1613000305
346,Salalah,17.0151,54.0924,73.40,38,0,8.05,OM,1613000312
356,Mango,27.9797,-82.3065,78.80,57,1,5.88,US,1613000314
371,La Huerta,19.4667,-104.6500,73.27,66,0,5.37,MX,1613000318
400,Pandan,14.0453,124.1694,79.38,84,11,7.87,PH,1613000324
424,Ikom,5.9667,8.7063,74.26,82,0,1.86,NG,1613000330
474,San Rafael,-34.6177,-68.3301,74.25,45,14,5.46,AR,1613000370
525,Nuevo Progreso,23.1667,-97.9500,78.01,61,10,4.00,MX,1613000382

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [8]:
#create hotel_df to store info
hotel_df = narrow_cities_df.loc[:,["City","Country", "Lat", "Lng"]]

#create and add the nuew column named Hotel Name to the df
hotel_df["Hotel Name"] = ""

hotel_df

               City Country      Lat       Lng Hotel Name
1      Saint-Pierre      RE -21.3393   55.4781
28   Saint-Philippe      RE -21.3585   55.7679
93         Belmonte      BR -15.8631  -38.8828
127  Cabo San Lucas      MX  22.8909 -109.9124
138          Niamey      NE  13.5137    2.1098
169         Arteaga      MX  18.4667 -102.4167
196  Lakes Entrance      AU -37.8811  147.9810
208         Sinaloa      MX  25.0000 -107.5000
256          Harper      LR   4.3750   -7.7169
309    Batemans Bay      AU -35.7167  150.1833
321           Ancud      CL -41.8697  -73.8203
346         Salalah      OM  17.0151   54.0924
356           Mango      US  27.9797  -82.3065
371       La Huerta      MX  19.4667 -104.6500
400          Pandan      PH  14.0453  124.1694
424            Ikom      NG   5.9667    8.7063
474      San Rafael      AR -34.6177  -68.3301
525  Nuevo Progreso      MX  23.1667  -97.9500

In [9]:
#making the request to find hotel near to the places on the df

for index, row in hotel_df.iterrows():
    try:
        
        base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
        params = {"type" : "hotel",
          "keyword" : "hotel",
          "radius" : 5000,
          "key" : g_key}

        lat = row['Lat']
        lng = row['Lng']
        
        params['location'] = f"{lat}, {lng}"
        
        hotel_data = requests.get(base_url, params=params).json()
        
        hotel_df.loc[index, "Hotel Name"] = hotel_data["results"][0]["name"]
        
    except (KeyError, IndexError):
        
        hotel_df.loc[index, "Hotel Name"] = "Not available"
        
hotel_df

,City,Country,Lat,Lng,Hotel Name
1,Saint-Pierre,RE,-21.3393,55.4781,LODGE PALMAE
28,Saint-Philippe,RE,-21.3585,55.7679,Les Embruns Du Baril
93,Belmonte,BR,-15.8631,-38.8828,Pousada do Diogo
127,Cabo San Lucas,MX,22.8909,-109.9124,The Bungalows Hotel
138,Niamey,NE,13.5137,2.1098,Bravia Hotel Niamey
169,Arteaga,MX,18.4667,-102.4167,Not available
196,Lakes Entrance,AU,-37.8811,147.9810,The Esplanade Resort & Spa
208,Sinaloa,MX,25.0000,-107.5000,Not available
256,Harper,LR,4.3750,-7.7169,Grands' Guesthouse
309,Batemans Bay,AU,-35.7167,150.1833,Bay Breeze Motel
321,Ancud,CL,-41.8697,-73.8203,Panamericana Hotel Ancud
346,Salalah,OM,17.0151,54.0924,Star Emirates garden villas
356,Mango,US,27.9797,-82.3065,Staybridge Suites Tampa East- Brandon
371,La Huerta,MX,19.4667,-104.6500,Not available
400,Pandan,PH,14.0453,124.1694,Bonifacio Lodge
424,Ikom,NG,5.9667,8.7063,Jorany Hotel Resort Ikom
474,San Rafael,AR,-34.6177,-68.3301,SAN MARTIN HOTEL Y SPA
525,Nuevo Progreso,MX,23.1667,-97.9500,Not available

In [10]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [11]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)

# Add the layer to the map
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))